// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// BridgeWebhookParams is parameters of bridgeWebhook operation.
type BridgeWebhookParams struct {
	ClientID string
}

func unpackBridgeWebhookParams(packed middleware.Parameters) (params BridgeWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "client_id",
			In:   "path",
		}
		params.ClientID = packed[key].(string)
	}
	return params
}

func decodeBridgeWebhookParams(args [1]string, argsEscaped bool, r *http.Request) (params BridgeWebhookParams, _ error) {
	// Decode path: client_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "client_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ClientID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "client_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
