// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.19.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
)

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// AccountEventsSubscriptionStatus invokes accountEventsSubscriptionStatus operation.
	//
	// Get a status of an account-events subscription.
	//
	// POST /account-events/subscription-status
	AccountEventsSubscriptionStatus(ctx context.Context, request *AccountEventsSubscriptionStatusReq) (*AccountEventsSubscriptionStatusOK, error)
	// BridgeWebhook invokes bridgeWebhook operation.
	//
	// Webhook called by the HTTP Bridge when an event occurs.
	//
	// POST /bridge/webhook/{client_id}
	BridgeWebhook(ctx context.Context, request *BridgeWebhookReq, params BridgeWebhookParams) error
	// GetTonConnectPayload invokes getTonConnectPayload operation.
	//
	// Get a challenge for TON Connect.
	//
	// GET /tonconnect/payload
	GetTonConnectPayload(ctx context.Context) (*GetTonConnectPayloadOK, error)
	// SubscribeToAccountEvents invokes subscribeToAccountEvents operation.
	//
	// Subscribe to notifications about events in the TON blockchain for a specific address.
	//
	// POST /account-events/subscribe
	SubscribeToAccountEvents(ctx context.Context, request *SubscribeToAccountEventsReq) error
	// SubscribeToBridgeEvents invokes subscribeToBridgeEvents operation.
	//
	// Subscribe to notifications from the HTTP Bridge regarding a specific smart contract or wallet.
	//
	// POST /bridge/subscribe
	SubscribeToBridgeEvents(ctx context.Context, request *SubscribeToBridgeEventsReq) error
	// UnsubscribeFromAccountEvents invokes unsubscribeFromAccountEvents operation.
	//
	// Unsubscribe from notifications about events in the TON blockchain for a specific address.
	//
	// POST /account-events/unsubscribe
	UnsubscribeFromAccountEvents(ctx context.Context, request *UnsubscribeFromAccountEventsReq) error
	// UnsubscribeFromBridgeEvents invokes unsubscribeFromBridgeEvents operation.
	//
	// Unsubscribe from bridge notifications.
	//
	// POST /bridge/unsubscribe
	UnsubscribeFromBridgeEvents(ctx context.Context, request *UnsubscribeFromBridgeEventsReq) error
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}
type errorHandler interface {
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

var _ Handler = struct {
	errorHandler
	*Client
}{}

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// AccountEventsSubscriptionStatus invokes accountEventsSubscriptionStatus operation.
//
// Get a status of an account-events subscription.
//
// POST /account-events/subscription-status
func (c *Client) AccountEventsSubscriptionStatus(ctx context.Context, request *AccountEventsSubscriptionStatusReq) (*AccountEventsSubscriptionStatusOK, error) {
	res, err := c.sendAccountEventsSubscriptionStatus(ctx, request)
	_ = res
	return res, err
}

func (c *Client) sendAccountEventsSubscriptionStatus(ctx context.Context, request *AccountEventsSubscriptionStatusReq) (res *AccountEventsSubscriptionStatusOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("accountEventsSubscriptionStatus"),
		semconv.HTTPMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/account-events/subscription-status"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "AccountEventsSubscriptionStatus",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/account-events/subscription-status"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeAccountEventsSubscriptionStatusRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeAccountEventsSubscriptionStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// BridgeWebhook invokes bridgeWebhook operation.
//
// Webhook called by the HTTP Bridge when an event occurs.
//
// POST /bridge/webhook/{client_id}
func (c *Client) BridgeWebhook(ctx context.Context, request *BridgeWebhookReq, params BridgeWebhookParams) error {
	res, err := c.sendBridgeWebhook(ctx, request, params)
	_ = res
	return err
}

func (c *Client) sendBridgeWebhook(ctx context.Context, request *BridgeWebhookReq, params BridgeWebhookParams) (res *BridgeWebhookOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("bridgeWebhook"),
		semconv.HTTPMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/bridge/webhook/{client_id}"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "BridgeWebhook",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/bridge/webhook/"
	{
		// Encode "client_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "client_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ClientID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeBridgeWebhookRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeBridgeWebhookResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetTonConnectPayload invokes getTonConnectPayload operation.
//
// Get a challenge for TON Connect.
//
// GET /tonconnect/payload
func (c *Client) GetTonConnectPayload(ctx context.Context) (*GetTonConnectPayloadOK, error) {
	res, err := c.sendGetTonConnectPayload(ctx)
	_ = res
	return res, err
}

func (c *Client) sendGetTonConnectPayload(ctx context.Context) (res *GetTonConnectPayloadOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getTonConnectPayload"),
		semconv.HTTPMethodKey.String("GET"),
		semconv.HTTPRouteKey.String("/tonconnect/payload"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "GetTonConnectPayload",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/tonconnect/payload"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeGetTonConnectPayloadResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SubscribeToAccountEvents invokes subscribeToAccountEvents operation.
//
// Subscribe to notifications about events in the TON blockchain for a specific address.
//
// POST /account-events/subscribe
func (c *Client) SubscribeToAccountEvents(ctx context.Context, request *SubscribeToAccountEventsReq) error {
	res, err := c.sendSubscribeToAccountEvents(ctx, request)
	_ = res
	return err
}

func (c *Client) sendSubscribeToAccountEvents(ctx context.Context, request *SubscribeToAccountEventsReq) (res *SubscribeToAccountEventsOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("subscribeToAccountEvents"),
		semconv.HTTPMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/account-events/subscribe"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "SubscribeToAccountEvents",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/account-events/subscribe"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSubscribeToAccountEventsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeSubscribeToAccountEventsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SubscribeToBridgeEvents invokes subscribeToBridgeEvents operation.
//
// Subscribe to notifications from the HTTP Bridge regarding a specific smart contract or wallet.
//
// POST /bridge/subscribe
func (c *Client) SubscribeToBridgeEvents(ctx context.Context, request *SubscribeToBridgeEventsReq) error {
	res, err := c.sendSubscribeToBridgeEvents(ctx, request)
	_ = res
	return err
}

func (c *Client) sendSubscribeToBridgeEvents(ctx context.Context, request *SubscribeToBridgeEventsReq) (res *SubscribeToBridgeEventsOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("subscribeToBridgeEvents"),
		semconv.HTTPMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/bridge/subscribe"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "SubscribeToBridgeEvents",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/bridge/subscribe"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSubscribeToBridgeEventsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeSubscribeToBridgeEventsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UnsubscribeFromAccountEvents invokes unsubscribeFromAccountEvents operation.
//
// Unsubscribe from notifications about events in the TON blockchain for a specific address.
//
// POST /account-events/unsubscribe
func (c *Client) UnsubscribeFromAccountEvents(ctx context.Context, request *UnsubscribeFromAccountEventsReq) error {
	res, err := c.sendUnsubscribeFromAccountEvents(ctx, request)
	_ = res
	return err
}

func (c *Client) sendUnsubscribeFromAccountEvents(ctx context.Context, request *UnsubscribeFromAccountEventsReq) (res *UnsubscribeFromAccountEventsOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("unsubscribeFromAccountEvents"),
		semconv.HTTPMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/account-events/unsubscribe"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "UnsubscribeFromAccountEvents",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/account-events/unsubscribe"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUnsubscribeFromAccountEventsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeUnsubscribeFromAccountEventsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UnsubscribeFromBridgeEvents invokes unsubscribeFromBridgeEvents operation.
//
// Unsubscribe from bridge notifications.
//
// POST /bridge/unsubscribe
func (c *Client) UnsubscribeFromBridgeEvents(ctx context.Context, request *UnsubscribeFromBridgeEventsReq) error {
	res, err := c.sendUnsubscribeFromBridgeEvents(ctx, request)
	_ = res
	return err
}

func (c *Client) sendUnsubscribeFromBridgeEvents(ctx context.Context, request *UnsubscribeFromBridgeEventsReq) (res *UnsubscribeFromBridgeEventsOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("unsubscribeFromBridgeEvents"),
		semconv.HTTPMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/bridge/unsubscribe"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "UnsubscribeFromBridgeEvents",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/bridge/unsubscribe"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUnsubscribeFromBridgeEventsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeUnsubscribeFromBridgeEventsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
