// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"

	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
)

// BridgeWebhookParams is parameters of bridgeWebhook operation.
type BridgeWebhookParams struct {
	ClientID string
}

func unpackBridgeWebhookParams(packed middleware.Parameters) (params BridgeWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "client_id",
			In:   "path",
		}
		params.ClientID = packed[key].(string)
	}
	return params
}

func decodeBridgeWebhookParams(args [0]string, argsEscaped bool, r *http.Request) (params BridgeWebhookParams, _ error) {
	// Decode path: client_id.
	if err := func() error {
		// Not used.
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "client_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
